# Generated by Django 3.0.6 on 2020-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20200520_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
